#include "LootGroups.h"

#include <log.h>
#include <safewritefile.h>
#include <utility.h>

#include <QFile>
#include <QRegularExpression>

#pragma warning(push)
#pragma warning(disable : 4459)
#undef emit
#include <ryml.hpp>
#pragma warning(pop)

#include <map>
#include <stdexcept>
#include <string>

using namespace Qt::Literals::StringLiterals;

namespace
{

// ryml's default error handler calls abort(), which took MO2 down with it
// whenever a LOOT masterlist contained YAML the parser rejects. Throwing
// instead makes the failure recoverable. The template detects which error
// API this ryml snapshot has (m_error before 2026, split handlers after).
template <typename Callbacks>
void installThrowingHandlers(Callbacks& callbacks)
{
  if constexpr (requires { callbacks.m_error_parse; }) {
    callbacks.m_error_basic = [](auto msg, auto const& /*errdata*/,
                                 void* /*user_data*/) {
      throw std::runtime_error(std::string(msg.str, msg.len));
    };
    callbacks.m_error_parse = [](auto msg, auto const& /*errdata*/,
                                 void* /*user_data*/) {
      throw std::runtime_error(std::string(msg.str, msg.len));
    };
    callbacks.m_error_visit = [](auto msg, auto const& /*errdata*/,
                                 void* /*user_data*/) {
      throw std::runtime_error(std::string(msg.str, msg.len));
    };
  } else {
    callbacks.m_error = [](const char* msg, size_t len, auto /*loc*/,
                           void* /*user_data*/) {
      throw std::runtime_error(std::string(msg, len));
    };
  }
}

struct RymlThrowOnError
{
  RymlThrowOnError() : previous{ryml::get_callbacks()}
  {
    ryml::Callbacks callbacks = previous;
    installThrowingHandlers(callbacks);
    ryml::set_callbacks(callbacks);
  }

  ~RymlThrowOnError() { ryml::set_callbacks(previous); }

  ryml::Callbacks previous;
};

}  // namespace

template<typename F>
static void commitSafeFile(F& file)
{
  if constexpr (requires(F& f) { f.commit(); }) {
    file.commit();
  } else {
    file->commit();
  }
}

namespace MOTools
{

static bool isRegex(const ryml::csubstr& key)
{
  return key.first_of(":\\*?|\"") != ryml::npos;
}

static void importLootGroups(const QString& lootconfig,
                             std::map<QString, QString>& groups)
{
  if (lootconfig.isEmpty()) {
    return;
  }

  QFile f{lootconfig};

  if (!f.open(QIODevice::ReadOnly)) {
    return;
  }

  auto buffer = f.readAll();

  try {
    const RymlThrowOnError errorGuard;

  ryml::Tree tree = ryml::parse_in_place(ryml::substr(buffer.data(), buffer.size()));
  tree.resolve();

  const std::size_t root_id = tree.root_id();
  if (!tree.is_map(root_id))
    return;

  const std::size_t plugins_id = tree.find_child(root_id, "plugins");
  if (plugins_id == ryml::npos || !tree.is_seq(plugins_id))
    return;

  for (std::size_t pos = 0, num = tree.num_children(plugins_id); pos < num; ++pos) {
    const std::size_t plugin_id = tree.child(plugins_id, pos);
    if (!tree.is_map(plugin_id))
      continue;

    const std::size_t group_id = tree.find_child(plugin_id, "group");
    if (group_id == ryml::npos)
      continue;

    const std::size_t name_id = tree.find_child(plugin_id, "name");
    if (name_id == ryml::npos)
      continue;

    const auto& name  = tree.val(name_id);
    const auto& group = tree.val(group_id);

    if (isRegex(name)) {
      const auto pattern = QString::fromLocal8Bit(name.data(), name.size());
      const auto re =
          QRegularExpression(pattern, QRegularExpression::CaseInsensitiveOption);
      for (auto it = groups.begin(); it != groups.end(); ++it) {
        const auto match = re.match(it->first);
        if (match.hasMatch()) {
          it->second = QString::fromLocal8Bit(group.data(), group.size());
        }
      }
    } else {
      const auto key = QString::fromLocal8Bit(name.data(), name.size());
      if (const auto it = groups.find(key); it != groups.end()) {
        it->second = QString::fromLocal8Bit(group.data(), group.size());
      }
    }
  }

  } catch (const std::exception& e) {
    MOBase::log::warn("failed to parse LOOT list \"{}\": {}",
                      lootconfig.toStdString(), e.what());
  }
}

static void writeGroups(const QString& plugingroups, std::map<QString, QString>& groups)
{
  QStringList knownGroups;
  QFile existingFile{plugingroups};
  if (existingFile.open(QIODevice::ReadOnly)) {
    QTextStream stream{&existingFile};
    QString line;
    while (stream.readLineInto(&line)) {
      if (line.isEmpty() || line.at(0) == u'#') {
        continue;
      }

      const auto fields = line.split(u'|');
      if (fields.count() == 2 && fields[0].isEmpty() && !fields[1].isEmpty() &&
          !knownGroups.contains(fields[1])) {
        knownGroups.append(fields[1]);
      }
    }


    existingFile.close();
  }

  MOBase::SafeWriteFile file{plugingroups};

  file->resize(0);
  file->write("# This file was automatically generated by Mod Organizer.\r\n"_ba);
  for (const auto& group : knownGroups) {
    file->write(u"|%1\r\n"_s.arg(group).toUtf8());
  }

  for (const auto& [plugin, group] : groups) {
    if (!group.isEmpty()) {
      file->write(u"%1|%2\r\n"_s.arg(plugin).arg(group).toUtf8());
    }
  }

  commitSafeFile(file);
}

void importLootGroups(const TESData::PluginList* pluginList,
                      const QString& plugingroups, const QString& masterlist,
                      const QString& userlist)
{
  MOBase::TimeThis tt{"importLootGroups"};

  std::map<QString, QString> groups;
  for (int id = 0, count = pluginList->pluginCount(); id < count; ++id) {
    const auto plugin = pluginList->getPlugin(id);
    groups.emplace(plugin->name(), "default");
  }

  importLootGroups(masterlist, groups);
  importLootGroups(userlist, groups);
  writeGroups(plugingroups, groups);
}

}  // namespace MOTools
